workflows:
  flutter-android:
    name: Build Flutter Android APK
    environment:
      flutter: stable
      android_signing:
        - release
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Build APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
    publishing:
      email:
        recipients:
          - user@example.com
